name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.8
      with: 
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: python-heroku-estudo
        usedocker: true
    - run: echo ${{ secrets.HEROKU_API_KEY }}
    - run: heroku auth:whoami
    - name: Build and push
      run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
    - name: Release
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 
