name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.8
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "python-heroku-estudo"
        heroku_email: "disalles222@hotmail.com"
        usedocker: true
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:push -a ${{secrets.HEROKU_APP_NAME}} web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web 
